categories:
  KuHdist:
    label: 'KIND&HUND Distribution'
  KuHdist.templates:
    label: 'Templates'
    parent: KuHdist
  KuHdist.pages:
    label: 'Pages'
    parent: KuHdist
  KuHdist.layout:
    label: 'Layout'
    parent: KuHdist
  KuHdist.settings:
    label: 'Settings'
    parent: KuHdist

settings:
  KuHdist.templateRootPath:
    label: 'Templates'
    category: KuHdist.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Templates/'
  KuHdist.partialRootPath:
    label: 'Partials'
    category: KuHdist.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Partials/'
  KuHdist.layoutRootPath:
    label: 'Layouts'
    category: KuHdist.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:blog_example/Resources/Private/Layouts/'
  KuHdist.loginPid:
    label: 'Default FE-User Login PID'
    category: KuHdist.pages
    description: 'Page containing fe_login Form'
    type: int
    default: 0
  KuHdist.editorUsergroupUid:
    label: 'Frontend admin user group UID'
    category: KuHdist.settings
    description: 'Enter the uid of the front end user group that should be allowed to edit blogs and post in the frontend in the admin plugin. '
    type: int
    default: 0
  KuHdist.postsPerPage:
    label: 'Posts per page'
    category: KuHdist.settings
    description: 'How many posts should be displayed per page of pagination?'
    type: int
    default: 3
  KuHdist.defaultGravator:
    label: 'Default gravator icon'
    category: KuHdist.layout
    description: 'This icon is displayed for a comment if the email address of the commentary is not registered. '
    type: string
    default: 'EXT:blog_example/Resources/Public/Icons/default_gravatar.gif'
