name: conpassione/detailpage
typeName: 36650012
title: Detailpage
group: conpassione
description: Das ist die Standard-Inhaltsseite
prefixFields: false
fields:
  - identifier: subtitle
    useExistingField: true


